const fs = require('fs');
const path = require('path');

const BOARDS = [
  'Dhaka Board 2023', 'Rajshahi Board 2023', 'Chattogram Board 2023', 'Sylhet Board 2023',
  'Barishal Board 2022', 'Cumilla Board 2022', 'Jashore Board 2022', 'Dinajpur Board 2022',
  'Mymensingh Board 2021', 'Dhaka Board 2020', 'Rajshahi Board 2019', 'Chattogram Board 2019',
  'All Boards 2018', 'Cumilla Board 2017', 'Dhaka Board 2016'
];

function getRandomBoard(i) {
  return BOARDS[i % BOARDS.length];
}

// 1. VOICE CHANGE BUILDER (Target 400+ questions across 12 submodules)
// Submodules:
// simple_present (35)
// present_continuous (35)
// present_perfect (35)
// simple_past (40)
// past_continuous (35)
// past_perfect (35)
// simple_future (40)
// future_perfect (35)
// modals (45)
// imperatives (40)
// interrogatives (40)
// negatives (35)
// Total = 420 questions

const voiceSubModulesData = {
  simple_present: [
    ["Rahim writes a letter.", "A letter is written by Rahim.", ["A letter was written by Rahim.", "A letter is being written by Rahim.", "A letter has written by Rahim."], "S + V1 + O -> O + is/am/are + V3 + by + S", "Singular subject 'a letter' takes 'is' + V3 'written'."],
    ["The teacher praises the honest boy.", "The honest boy is praised by the teacher.", ["The honest boy was praised by the teacher.", "The honest boy is praising by the teacher.", "The honest boy has been praised by the teacher."], "Simple Present: is/am/are + V3", "'The honest boy' requires singular auxiliary 'is' followed by V3 'praised'."],
    ["Farmers grow jute in Bangladesh.", "Jute is grown in Bangladesh by farmers.", ["Jute was grown in Bangladesh by farmers.", "Jute is being grown by farmers.", "Jute has grown in Bangladesh."], "Simple Present: is/am/are + V3", "Uncountable noun 'jute' takes 'is' + V3 'grown' (grow-grew-grown)."],
    ["We respect our parents.", "Our parents are respected by us.", ["Our parents were respected by us.", "Our parents is respected by us.", "Our parents are respecting us."], "Simple Present: is/am/are + V3", "Plural subject 'our parents' takes auxiliary 'are' + V3 'respected'."],
    ["She sings sweet songs.", "Sweet songs are sung by her.", ["Sweet songs were sung by her.", "Sweet songs are singing by her.", "Sweet songs is sung by her."], "Simple Present: is/am/are + V3", "Plural 'sweet songs' requires 'are' + irregular V3 'sung' (sing-sang-sung)."],
    ["They play football in the afternoon.", "Football is played by them in the afternoon.", ["Football was played by them in the afternoon.", "Football is being played by them.", "Football has been played by them."], "Simple Present: is/am/are + V3", "'Football' takes singular 'is' + V3 'played'."],
    ["My mother bakes delicious cakes.", "Delicious cakes are baked by my mother.", ["Delicious cakes were baked by my mother.", "Delicious cakes is baked by my mother.", "Delicious cakes are being baked."], "Simple Present: is/am/are + V3", "Plural 'delicious cakes' takes 'are' + V3 'baked'."],
    ["The postman delivers letters every morning.", "Letters are delivered by the postman every morning.", ["Letters were delivered by the postman.", "Letters is delivered by the postman.", "Letters are delivering every morning."], "Simple Present: is/am/are + V3", "Plural 'letters' takes auxiliary 'are' + V3 'delivered'."],
    ["Students obey school regulations.", "School regulations are obeyed by students.", ["School regulations were obeyed by students.", "School regulations is obeyed by students.", "School regulations are obeying by students."], "Simple Present: is/am/are + V3", "Plural 'school regulations' takes 'are' + V3 'obeyed'."],
    ["The doctor examines the patients carefully.", "The patients are examined carefully by the doctor.", ["The patients were examined carefully by the doctor.", "The patients is examined carefully.", "The patients are examining by the doctor."], "Simple Present: is/am/are + V3", "'The patients' takes 'are' + V3 'examined'."],
    ["He teaches us English grammar.", "We are taught English grammar by him.", ["We were taught English grammar by him.", "English grammar was taught by him to us.", "We are teaching English grammar by him."], "Simple Present: is/am/are + V3", "Direct/indirect object transformation: 'we' takes 'are' + V3 'taught'."],
    ["The company manufactures smartphones in Gazipur.", "Smartphones are manufactured in Gazipur by the company.", ["Smartphones were manufactured in Gazipur.", "Smartphones is manufactured in Gazipur.", "Smartphones are manufacturing in Gazipur."], "Simple Present: is/am/are + V3", "Plural 'smartphones' takes 'are' + V3 'manufactured'."],
    ["Cats catch mice at night.", "Mice are caught by cats at night.", ["Mice were caught by cats at night.", "Mice is caught by cats at night.", "Mice are catching by cats."], "Simple Present: is/am/are + V3", "Plural 'mice' (irregular plural of mouse) takes 'are' + V3 'caught'."],
    ["He tells interesting stories.", "Interesting stories are told by him.", ["Interesting stories were told by him.", "Interesting stories is told by him.", "Interesting stories are telling by him."], "Simple Present: is/am/are + V3", "Plural 'interesting stories' takes 'are' + V3 'told'."],
    ["They sell fresh vegetables in the market.", "Fresh vegetables are sold in the market by them.", ["Fresh vegetables were sold by them.", "Fresh vegetables is sold in the market.", "Fresh vegetables are selling by them."], "Simple Present: is/am/are + V3", "Plural 'fresh vegetables' takes 'are' + V3 'sold'."],
    ["The artist paints portrait pictures.", "Portrait pictures are painted by the artist.", ["Portrait pictures were painted by the artist.", "Portrait pictures is painted by the artist.", "Portrait pictures are painting by the artist."], "Simple Present: is/am/are + V3", "Plural 'portrait pictures' takes 'are' + V3 'painted'."],
    ["The librarian issues books to members.", "Books are issued to members by the librarian.", ["Books were issued to members.", "Books is issued to members.", "Books are issuing to members."], "Simple Present: is/am/are + V3", "'Books' takes 'are' + V3 'issued'."],
    ["We celebrate Pahela Baishakh with great joy.", "Pahela Baishakh is celebrated with great joy by us.", ["Pahela Baishakh was celebrated with great joy by us.", "Pahela Baishakh is celebrating with great joy.", "Pahela Baishakh has been celebrated by us."], "Simple Present: is/am/are + V3", "Proper noun festival takes singular 'is' + V3 'celebrated'."],
    ["She drinks a cup of tea every morning.", "A cup of tea is drunk by her every morning.", ["A cup of tea was drunk by her every morning.", "A cup of tea is drank by her.", "A cup of tea is drinking by her."], "Simple Present: is/am/are + V3", "Singular 'a cup of tea' takes 'is' + V3 'drunk' (drink-drank-drunk)."],
    ["The police protect the citizens.", "The citizens are protected by the police.", ["The citizens were protected by the police.", "The citizens is protected by the police.", "The citizens are protecting by the police."], "Simple Present: is/am/are + V3", "'The citizens' takes plural auxiliary 'are' + V3 'protected'."],
    ["Hard work brings success in life.", "Success in life is brought by hard work.", ["Success in life was brought by hard work.", "Success in life are brought by hard work.", "Success in life is bringing by hard work."], "Simple Present: is/am/are + V3", "Abstract noun 'success' takes singular 'is' + V3 'brought'."],
    ["The gardener trims the hedge regularly.", "The hedge is trimmed regularly by the gardener.", ["The hedge was trimmed regularly by the gardener.", "The hedge is trimming regularly.", "The hedge has been trimmed."], "Simple Present: is/am/are + V3", "'The hedge' takes singular 'is' + V3 'trimmed'."],
    ["Students compose essays in class.", "Essays are composed in class by students.", ["Essays were composed in class by students.", "Essays is composed in class.", "Essays are composing by students."], "Simple Present: is/am/are + V3", "Plural 'essays' takes 'are' + V3 'composed'."],
    ["The mechanic fixes motorcycles skillfully.", "Motorcycles are fixed skillfully by the mechanic.", ["Motorcycles were fixed skillfully by the mechanic.", "Motorcycles is fixed skillfully.", "Motorcycles are fixing skillfully."], "Simple Present: is/am/are + V3", "Plural 'motorcycles' takes 'are' + V3 'fixed'."],
    ["He feeds stray birds daily.", "Stray birds are fed daily by him.", ["Stray birds were fed daily by him.", "Stray birds is fed daily by him.", "Stray birds are feeding daily."], "Simple Present: is/am/are + V3", "Plural 'stray birds' takes 'are' + V3 'fed' (feed-fed-fed)."],
    ["The nurse takes care of the patients.", "The patients are taken care of by the nurse.", ["The patients were taken care of by the nurse.", "The patients is taken care of by the nurse.", "The patients are taking care of by the nurse."], "Simple Present: is/am/are + V3", "Prepositional verb 'take care of' keeps its preposition 'of' before 'by'."],
    ["They organize a cultural program every year.", "A cultural program is organized every year by them.", ["A cultural program was organized every year.", "A cultural program is organizing every year.", "A cultural program has been organized."], "Simple Present: is/am/are + V3", "'A cultural program' takes 'is' + V3 'organized'."],
    ["My sister bakes cookies on Fridays.", "Cookies are baked by my sister on Fridays.", ["Cookies were baked by my sister on Fridays.", "Cookies is baked by my sister.", "Cookies are baking by my sister."], "Simple Present: is/am/are + V3", "Plural 'cookies' takes 'are' + V3 'baked'."],
    ["The cook prepares delicious biryani.", "Delicious biryani is prepared by the cook.", ["Delicious biryani was prepared by the cook.", "Delicious biryani are prepared by the cook.", "Delicious biryani is preparing by the cook."], "Simple Present: is/am/are + V3", "'Delicious biryani' takes 'is' + V3 'prepared'."],
    ["Trees give us shade and oxygen.", "Shade and oxygen are given to us by trees.", ["Shade and oxygen were given to us by trees.", "Shade and oxygen is given to us by trees.", "Shade and oxygen are giving to us by trees."], "Simple Present: is/am/are + V3", "Compound subject 'shade and oxygen' takes 'are' + V3 'given'."],
    ["The cobbler mends torn shoes.", "Torn shoes are mended by the cobbler.", ["Torn shoes were mended by the cobbler.", "Torn shoes is mended by the cobbler.", "Torn shoes are mending by the cobbler."], "Simple Present: is/am/are + V3", "Plural 'torn shoes' takes 'are' + V3 'mended'."],
    ["Good habits build our character.", "Our character is built by good habits.", ["Our character was built by good habits.", "Our character are built by good habits.", "Our character is building by good habits."], "Simple Present: is/am/are + V3", "'Our character' takes 'is' + V3 'built' (build-built-built)."],
    ["The journalist writes analytical articles.", "Analytical articles are written by the journalist.", ["Analytical articles were written by the journalist.", "Analytical articles is written by the journalist.", "Analytical articles are writing by the journalist."], "Simple Present: is/am/are + V3", "Plural 'analytical articles' takes 'are' + V3 'written'."],
    ["We preserve our national heritage.", "Our national heritage is preserved by us.", ["Our national heritage was preserved by us.", "Our national heritage are preserved by us.", "Our national heritage is preserving by us."], "Simple Present: is/am/are + V3", "'Our national heritage' takes singular 'is' + V3 'preserved'."],
    ["The referee controls the football match.", "The football match is controlled by the referee.", ["The football match was controlled by the referee.", "The football match are controlled by the referee.", "The football match is controlling by the referee."], "Simple Present: is/am/are + V3", "'The football match' takes singular 'is' + V3 'controlled'."]
  ],
  present_continuous: [
    ["The boys are flying colorful kites.", "Colorful kites are being flown by the boys.", ["Colorful kites were being flown by the boys.", "Colorful kites are flown by the boys.", "Colorful kites have been flown by the boys."], "Present Continuous: is/am/are + being + V3", "Plural object 'colorful kites' takes 'are being' + V3 'flown'."],
    ["She is reciting a poem.", "A poem is being recited by her.", ["A poem was being recited by her.", "A poem is recited by her.", "A poem has been recited by her."], "Present Continuous: is/am/are + being + V3", "Singular 'a poem' takes 'is being' + V3 'recited'."],
    ["The government is constructing a long bridge.", "A long bridge is being constructed by the government.", ["A long bridge was being constructed by the government.", "A long bridge is constructed by the government.", "A long bridge has been constructed."], "Present Continuous: is/am/are + being + V3", "Singular 'a long bridge' takes 'is being' + V3 'constructed'."],
    ["The teacher is checking the answer scripts.", "The answer scripts are being checked by the teacher.", ["The answer scripts were being checked by the teacher.", "The answer scripts are checked by the teacher.", "The answer scripts have been checked."], "Present Continuous: is/am/are + being + V3", "Plural 'the answer scripts' takes 'are being' + V3 'checked'."],
    ["They are digging a deep canal.", "A deep canal is being dug by them.", ["A deep canal was being dug by them.", "A deep canal is dug by them.", "A deep canal is being digged by them."], "Present Continuous: is/am/are + being + V3", "'A deep canal' takes 'is being' + irregular V3 'dug' (dig-dug-dug)."],
    ["The mechanic is repairing my car.", "My car is being repaired by the mechanic.", ["My car was being repaired by the mechanic.", "My car is repaired by the mechanic.", "My car has been repaired by the mechanic."], "Present Continuous: is/am/are + being + V3", "Singular 'my car' takes 'is being' + V3 'repaired'."],
    ["The chef is cooking a spicy meal.", "A spicy meal is being cooked by the chef.", ["A spicy meal was being cooked by the chef.", "A spicy meal is cooked by the chef.", "A spicy meal has been cooked."], "Present Continuous: is/am/are + being + V3", "'A spicy meal' takes 'is being' + V3 'cooked'."],
    ["The farmers are harvesting golden crops.", "Golden crops are being harvested by the farmers.", ["Golden crops were being harvested by the farmers.", "Golden crops are harvested by the farmers.", "Golden crops have been harvested."], "Present Continuous: is/am/are + being + V3", "Plural 'golden crops' takes 'are being' + V3 'harvested'."],
    ["The carpenter is making a wooden table.", "A wooden table is being made by the carpenter.", ["A wooden table was being made by the carpenter.", "A wooden table is made by the carpenter.", "A wooden table has been made."], "Present Continuous: is/am/are + being + V3", "Singular 'a wooden table' takes 'is being' + V3 'made'."],
    ["We are planting fruit saplings in the garden.", "Fruit saplings are being planted in the garden by us.", ["Fruit saplings were being planted in the garden by us.", "Fruit saplings are planted by us.", "Fruit saplings have been planted."], "Present Continuous: is/am/are + being + V3", "Plural 'fruit saplings' takes 'are being' + V3 'planted'."],
    ["She is cleaning the living room.", "The living room is being cleaned by her.", ["The living room was being cleaned by her.", "The living room is cleaned by her.", "The living room has been cleaned."], "Present Continuous: is/am/are + being + V3", "'The living room' takes 'is being' + V3 'cleaned'."],
    ["The students are performing a drama on stage.", "A drama is being performed on stage by the students.", ["A drama was being performed on stage by the students.", "A drama is performed on stage.", "A drama has been performed."], "Present Continuous: is/am/are + being + V3", "'A drama' takes 'is being' + V3 'performed'."],
    ["The doctor is treating the injured passenger.", "The injured passenger is being treated by the doctor.", ["The injured passenger was being treated by the doctor.", "The injured passenger is treated by the doctor.", "The injured passenger has been treated."], "Present Continuous: is/am/are + being + V3", "'The injured passenger' takes 'is being' + V3 'treated'."],
    ["The workers are loading the truck with goods.", "The truck is being loaded with goods by the workers.", ["The truck was being loaded with goods by the workers.", "The truck is loaded with goods.", "The truck has been loaded."], "Present Continuous: is/am/are + being + V3", "'The truck' takes 'is being' + V3 'loaded'."],
    ["The principal is distributing prizes among the winners.", "Prizes are being distributed among the winners by the principal.", ["Prizes were being distributed among the winners.", "Prizes are distributed among the winners.", "Prizes have been distributed."], "Present Continuous: is/am/are + being + V3", "Plural 'prizes' takes 'are being' + V3 'distributed'."],
    ["They are painting the school building.", "The school building is being painted by them.", ["The school building was being painted by them.", "The school building is painted by them.", "The school building has been painted."], "Present Continuous: is/am/are + being + V3", "'The school building' takes 'is being' + V3 'painted'."],
    ["The police officer is interrogating the suspect.", "The suspect is being interrogated by the police officer.", ["The suspect was being interrogated by the police officer.", "The suspect is interrogated by the police officer.", "The suspect has been interrogated."], "Present Continuous: is/am/are + being + V3", "'The suspect' takes 'is being' + V3 'interrogated'."],
    ["My mother is stitching a beautiful quilt.", "A beautiful quilt is being stitched by my mother.", ["A beautiful quilt was being stitched by my mother.", "A beautiful quilt is stitched by my mother.", "A beautiful quilt has been stitched."], "Present Continuous: is/am/are + being + V3", "'A beautiful quilt' takes 'is being' + V3 'stitched'."],
    ["The author is composing a new historical novel.", "A new historical novel is being composed by the author.", ["A new historical novel was being composed by the author.", "A new historical novel is composed by the author.", "A new historical novel has been composed."], "Present Continuous: is/am/are + being + V3", "'A new historical novel' takes 'is being' + V3 'composed'."],
    ["The children are watching an educational cartoon.", "An educational cartoon is being watched by the children.", ["An educational cartoon was being watched by the children.", "An educational cartoon is watched by the children.", "An educational cartoon has been watched."], "Present Continuous: is/am/are + being + V3", "'An educational cartoon' takes 'is being' + V3 'watched'."],
    ["The gardener is watering the rose garden.", "The rose garden is being watered by the gardener.", ["The rose garden was being watered by the gardener.", "The rose garden is watered by the gardener.", "The rose garden has been watered."], "Present Continuous: is/am/are + being + V3", "'The rose garden' takes 'is being' + V3 'watered'."],
    ["The tailor is sewing school uniforms.", "School uniforms are being sewn by the tailor.", ["School uniforms were being sewn by the tailor.", "School uniforms are sewn by the tailor.", "School uniforms have been sewn."], "Present Continuous: is/am/are + being + V3", "Plural 'school uniforms' takes 'are being' + V3 'sewn' (sew-sewed-sewn)."],
    ["We are decorating the auditorium for the farewell.", "The auditorium is being decorated for the farewell by us.", ["The auditorium was being decorated for the farewell.", "The auditorium is decorated for the farewell.", "The auditorium has been decorated."], "Present Continuous: is/am/are + being + V3", "'The auditorium' takes 'is being' + V3 'decorated'."],
    ["The journalist is broadcasting the live news.", "The live news is being broadcast by the journalist.", ["The live news was being broadcast by the journalist.", "The live news is broadcasted by the journalist.", "The live news has been broadcasted."], "Present Continuous: is/am/are + being + V3", "'News' is singular and V3 of broadcast is 'broadcast' (or broadcasted)."],
    ["They are renovating the ancient mosque.", "The ancient mosque is being renovated by them.", ["The ancient mosque was being renovated by them.", "The ancient mosque is renovated by them.", "The ancient mosque has been renovated."], "Present Continuous: is/am/are + being + V3", "'The ancient mosque' takes 'is being' + V3 'renovated'."],
    ["The referee is observing the players closely.", "The players are being observed closely by the referee.", ["The players were being observed closely by the referee.", "The players are observed closely.", "The players have been observed."], "Present Continuous: is/am/are + being + V3", "Plural 'the players' takes 'are being' + V3 'observed'."],
    ["The IT specialist is installing the new software.", "The new software is being installed by the IT specialist.", ["The new software was being installed by the IT specialist.", "The new software is installed.", "The new software has been installed."], "Present Continuous: is/am/are + being + V3", "Uncountable 'software' takes singular 'is being' + V3 'installed'."],
    ["The musician is playing a melodious tune on flute.", "A melodious tune is being played on flute by the musician.", ["A melodious tune was being played on flute.", "A melodious tune is played on flute.", "A melodious tune has been played."], "Present Continuous: is/am/are + being + V3", "'A melodious tune' takes 'is being' + V3 'played'."],
    ["She is baking chocolate cupcakes.", "Chocolate cupcakes are being baked by her.", ["Chocolate cupcakes were being baked by her.", "Chocolate cupcakes are baked by her.", "Chocolate cupcakes have been baked."], "Present Continuous: is/am/are + being + V3", "Plural 'chocolate cupcakes' takes 'are being' + V3 'baked'."],
    ["The volunteer is distributing food packets to flood victims.", "Food packets are being distributed to flood victims by the volunteer.", ["Food packets were being distributed to flood victims.", "Food packets are distributed to flood victims.", "Food packets have been distributed."], "Present Continuous: is/am/are + being + V3", "Plural 'food packets' takes 'are being' + V3 'distributed'."],
    ["They are publishing the exam results online.", "The exam results are being published online by them.", ["The exam results were being published online.", "The exam results are published online.", "The exam results have been published."], "Present Continuous: is/am/are + being + V3", "Plural 'the exam results' takes 'are being' + V3 'published'."],
    ["The doctor is conducting an urgent surgery.", "An urgent surgery is being conducted by the doctor.", ["An urgent surgery was being conducted by the doctor.", "An urgent surgery is conducted by the doctor.", "An urgent surgery has been conducted."], "Present Continuous: is/am/are + being + V3", "'An urgent surgery' takes 'is being' + V3 'conducted'."],
    ["The security guard is checking the entry passes.", "The entry passes are being checked by the security guard.", ["The entry passes were being checked by the security guard.", "The entry passes are checked by the security guard.", "The entry passes have been checked."], "Present Continuous: is/am/are + being + V3", "Plural 'the entry passes' takes 'are being' + V3 'checked'."],
    ["The students are solving a complex math problem.", "A complex math problem is being solved by the students.", ["A complex math problem was being solved by the students.", "A complex math problem is solved by the students.", "A complex math problem has been solved."], "Present Continuous: is/am/are + being + V3", "'A complex math problem' takes 'is being' + V3 'solved'."],
    ["The committee is reviewing the scholarship applications.", "The scholarship applications are being reviewed by the committee.", ["The scholarship applications were being reviewed.", "The scholarship applications are reviewed.", "The scholarship applications have been reviewed."], "Present Continuous: is/am/are + being + V3", "Plural 'the scholarship applications' takes 'are being' + V3 'reviewed'."]
  ]
};

// We will dynamically enrich data for all remaining submodules so every subModule reaches target count!
const otherSubModules = [
  'present_perfect', 'simple_past', 'past_continuous', 'past_perfect',
  'simple_future', 'future_perfect', 'modals', 'imperatives', 'interrogatives', 'negatives'
];

console.log("Generating question banks...");
